## Importing libraries

In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\senas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

## Loading dataset

In [2]:
df = pd.read_csv('./../data/processed/20newsgroup_preprocessed.csv', on_bad_lines='skip', delimiter=";")
print(df.shape)
df.head(20)

(18828, 3)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,atheist resources addresses atheist organizati...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,begin pgp signed message introduction atheism ...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article charley wingate writes well john quite...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,kings become philosophers philosophers become ...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,article bob mcgwier writes however hate econom...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article writes didnt say lucifer created perfe...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes motto originated starspang...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article gregg jaeger writes victimized muslims...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,reference line trimmed jon livesey writes good...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,keith ryan writes people keep asking questions...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,jon livesey writes long motto stay around beco...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,kent sandvik writes borrow philosophy dont tru...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes discuss merits racism psyc...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes dont know capital pun...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes think people approve ...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes kill person innocent ...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,article james f tims writes maintaining classe...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,article fred rice writes propose two trends gr...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,article ken arromdee writes article jon livese...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,article brad porter writes science wonderful a...

## Checking for empty values

In [3]:
df.isnull().sum()

target           0
text             0
text_cleaned    36
dtype: int64

## Restructuring dataset
### Remove copy text into text_cleaned column.

In [4]:
df['text_cleaned'] = df['text']
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,From: mathew <mathew@mantis.co.uk>\nSubject: A...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,From: mathew <mathew@mantis.co.uk>\nSubject: A...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,From: mathew <mathew@mantis.co.uk>\nSubject: R...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,From: keith@cco.caltech.edu (Keith Allan Schne...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,Subject: Re: Don't more innocents die without ...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,Subject: Re: Ancient islamic rituals\nFrom: bo...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,Subject: Re: <Political Atheists?\nFrom: bobbe...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,Subject: Re: There must be a creator! (Maybe)\...

## Preprocessing text

### Removing headers from text.

In [5]:
# Remove text until the second empty line
# df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'^(?:.*\n)*?\s*?\n(?:.*\n)*?\s*?\n', '', x, count=1))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'^(?:.*\n)*?\s*?\n', '', x, count=1))
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/resources\nAlt-atheism-a...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/introduction\nAlt-atheis...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <65974@mimsy.umd.edu>\nmangoe@cs.um...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,dmn@kepler.unh.edu (...until kings become phil...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,In article <N4HY.93Apr5120934@harder.ccr-p.ida...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <1993Apr5.091139.823@batman.bmd.trw...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,arromdee@jyusenkyou.cs.jhu.edu (Ken Arromdee) ...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <114127@bu.edu>\njaeger@buphy.bu.ed...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(reference line trimmed)\n\nlivesey@solntze.wp...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,kmr4@po.CWRU.edu (Keith M. Ryan) writes:\n\n>>...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,livesey@solntze.wpd.sgi.com (Jon Livesey) writ...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,sandvik@newton.apple.com (Kent Sandvik) writes...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,arromdee@jyusenkyou.cs.jhu.edu (Ken Arromdee) ...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,In article <2942881697.0.p00168@psilink.com> p...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,In article <1993Apr3.081052.11292@monu6.cc.mon...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,In article <1993Apr3.212139.14076@blaze.cs.jhu...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,"In article <16BA1E927.DRPORTER@SUVM.SYR.EDU>, ..."

### Removing stopwords.

In [6]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stop_words])
    
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: remove_stopwords(x))
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/resources Alt-atheism-ar...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/introduction Alt-atheism...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <65974@mimsy.umd.edu> mangoe@cs.umd...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,dmn@kepler.unh.edu (...until kings become phil...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,In article <N4HY.93Apr5120934@harder.ccr-p.ida...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <1993Apr5.091139.823@batman.bmd.trw...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,arromdee@jyusenkyou.cs.jhu.edu (Ken Arromdee) ...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <114127@bu.edu> jaeger@buphy.bu.edu...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(reference line trimmed) livesey@solntze.wpd.s...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,kmr4@po.CWRU.edu (Keith M. Ryan) writes: >>The...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,livesey@solntze.wpd.sgi.com (Jon Livesey) writ...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,sandvik@newton.apple.com (Kent Sandvik) writes...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,arromdee@jyusenkyou.cs.jhu.edu (Ken Arromdee) ...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,bobbe@vice.ICO.TEK.COM (Robert Beauchaine) wri...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,In article <2942881697.0.p00168@psilink.com> p...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,In article <1993Apr3.081052.11292@monu6.cc.mon...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,In article <1993Apr3.212139.14076@blaze.cs.jhu...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,"In article <16BA1E927.DRPORTER@SUVM.SYR.EDU>, ..."

### Removing emails and phone numbers.

In [7]:
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\b[\w\-.]+?@[a-zA-Z0-9]+?(\.[a-zA-Z0-9-]+?){1,4}\b', '', x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\b\d{10}\b', '', x))
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/resources Alt-atheism-ar...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,Archive-name: atheism/introduction Alt-atheism...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <> (Charley Wingate) writes: >>Wel...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,(...until kings become philosophers philosoph...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,"In article <-p.ida.org>, -p.ida.org (Bob McGwi..."
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <> writes: >> Didn't say Lucifer c...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Ken Arromdee) writes: >>The motto originated...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,In article <> (Gregg Jaeger) writes: >>When v...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(reference line trimmed) (Jon Livesey) writes...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Keith M. Ryan) writes: >>Then people keep as...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Jon Livesey) writes: >>>How long [the motto]...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Kent Sandvik) writes: >>To borrow philosophy...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,"(Ken Arromdee) writes: >>But, discuss merits ..."
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,"(Robert Beauchaine) writes: >>But, know capit..."
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Robert Beauchaine) writes: >>I think 70% (or...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,(Robert Beauchaine) writes: >>If I kill perso...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,In article <> (James F. Tims) writes: > >By m...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,In article <> (Fred Rice) writes: >I propose ...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,In article <> (Ken Arromdee) writes: >In arti...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,"In article <>, (Brad Porter) writes: > > Scie..."

### Removing special characters, line breaks and extra whitespaces then convert to lowercase.

In [8]:
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\n', ' ', x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\s+', ' ', x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: x.lower())
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,archivename atheismresources altatheismarchive...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,archivename atheismintroduction altatheismarch...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,in article charley wingate writes well john qu...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,until kings become philosophers philosophers ...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,in article pidaorg pidaorg bob mcgwier writes ...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,in article writes didnt say lucifer created pe...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes the motto originated star...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,in article gregg jaeger writes when victimized...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,reference line trimmed jon livesey writes ther...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,keith m ryan writes then people keep asking q...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,jon livesey writes how long the motto stay ar...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,kent sandvik writes to borrow philosophy trul...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes but discuss merits racism...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes but know capital pun...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes i think 70 or so peo...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes if i kill person an ...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,in article james f tims writes by maintaining ...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,in article fred rice writes i propose that two...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,in article ken arromdee writes in article 1pj9...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,in article brad porter writes science wonderfu...

### Remove remaining numbers and stopwords.

In [9]:
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\b\w*\d\w*\b', '', x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: remove_stopwords(x))
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'(\w)\1{2,}', r'\1', x)) 
df['text_cleaned'] = df['text_cleaned'].apply(lambda x: re.sub(r'\b\w{2}\b', '', x).strip())
df.head(20)

,target,text,text_cleaned
0,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,archivename atheismresources altatheismarchive...
1,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: A...,archivename atheismintroduction altatheismarch...
2,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article charley wingate writes well john quite...
3,alt.atheism,From: mathew <mathew@mantis.co.uk>\nSubject: R...,kings become philosophers philosophers become ...
4,alt.atheism,From: strom@Watson.Ibm.Com (Rob Strom)\nSubjec...,article pidaorg pidaorg bob mcgwier writes how...
5,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article writes didnt say lucifer created perfe...
6,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes motto originated starspang...
7,alt.atheism,From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...,article gregg jaeger writes victimized muslims...
8,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,reference line trimmed jon livesey writes good...
9,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,keith ryan writes people keep asking questions...
10,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,jon livesey writes long motto stay around beco...
11,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,kent sandvik writes borrow philosophy truly un...
12,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,ken arromdee writes discuss merits racism psyc...
13,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes know capital punishme...
14,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes think people approve ...
15,alt.atheism,From: keith@cco.caltech.edu (Keith Allan Schne...,robert beauchaine writes kill person innocent ...
16,alt.atheism,Subject: Re: Don't more innocents die without ...,article james f tims writes maintaining classe...
17,alt.atheism,Subject: Re: Ancient islamic rituals\nFrom: bo...,article fred rice writes propose two trends gr...
18,alt.atheism,Subject: Re: <Political Atheists?\nFrom: bobbe...,article ken arromdee writes article jon livese...
19,alt.atheism,Subject: Re: There must be a creator! (Maybe)\...,article brad porter writes science wonderful a...

In [36]:
df.shape

(18828, 3)

## Saving preprocessed dataset

In [10]:
df.to_csv('./../data/processed/20newsgroup_preprocessed_own.csv', sep=';', index=False)